package com.lsh.bokeadmin.entry;

import java.sql.Timestamp;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

/**
 * categorys
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
public class Categorys implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3030603292572745467L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    private Integer cateId;

    private String cateName;

    private String description;

    private Timestamp createTime;

    private Integer parentCateId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public Integer getCateId() {
        return this.cateId;
    }

    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    public String getCateName() {
        return this.cateName;
    }

    public void setCateName(String cateName) {
        this.cateName = cateName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Integer getParentCateId() {
        return this.parentCateId;
    }

    public void setParentCateId(Integer parentCateId) {
        this.parentCateId = parentCateId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    /* This code was generated by TableGo tools, mark 3 begin. */

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }

    /* This code was generated by TableGo tools, mark 3 end. */
}