package com.lsh.bokeadmin.entry;

import java.sql.Timestamp;

import com.baomidou.mybatisplus.annotation.TableId;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

/**
 * 标签(labels)
 * 
 * @author bianj
 * @version 1.0.0 2021-03-31
 */
public class Labels implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6969043620598826403L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    @TableId
    private int labelId;

    private String labelName;

    private String description;

    private Timestamp createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public int getLabelId() {
        return this.labelId;
    }

    public void setLabelId(int labelId) {
        this.labelId = labelId;
    }

    public String getLabelName() {
        return this.labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    /* This code was generated by TableGo tools, mark 3 begin. */

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }

    /* This code was generated by TableGo tools, mark 3 end. */
}